config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#show"

  resources :time_logs
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  validates_presence_of :name

  has_many :time_logs
  has_many :organizations
end

app/models/time_log.rb
# frozen_string_literal: true

class TimeLog < ApplicationRecord
  enum week_days: [:MONDAY, :TUESDAY, :WEDNESDAY, :THURSDAY, :FRIDAY].freeze
  enum meal_times: [
    :BREAKFAST,
    :LUNCH,
    :DINNER
  ].freeze

  belongs_to :user
  belongs_to :organization

  scope :recent_logs, -> { order(created_at: :desc) }

  validates_presence_of :week_day, :purpose, :time_in
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates_presence_of :first_name, :last_name
  has_many :time_logs
  belongs_to :organization

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, 
      keys: [:first_name, :last_name, :organization_id]
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    render 'show'
  end
end

app/controllers/time_logs_controller.rb
# frozen_string_literal: true

class TimeLogsController < ApplicationController
  def new
    @time_log = TimeLog.new
  end

  def create
    @time_log = TimeLog.new(time_log_params)

    if @time_log.save
      redirect_to time_logs_path
    else
      render 'new'
      flash[:error] = 'Failed to save time log'
    end
  end

  def show
    @time_log = TimeLog.find(params[:id])
  end

  def edit
    @time_log = TimeLog.find(params[:id])
  end

  def update
    @time_log = TimeLog.find(params[:id])
    if @time_log.update(time_log_params)
      redirect_to time_logs_path
    end
  end

  def index
    @current_week_logs = TimeLog.where(user_id: current_user.id).recent_logs
  end

  private

  def time_log_params
    params.require(:time_log).permit(
      :week_day, :time_in, :time_out, :purpose, :comments,
      :user_id, :organization_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def humanize_week_day(week_day)
    TimeLog.week_days.key(week_day).capitalize
  end

  def humanize_purpose(purpose)
    TimeLog.meal_times.key(purpose).capitalize
  end
end

app/views/home/show.html.erb
<div class="home"> 
  <% if user_signed_in? %>
    <h1 class="home__header">Clock In-Out Application For <%=current_user.organization.name %>  </h1>
    <p>  
      <%= link_to 'Clock In', new_time_log_path %>        
    </p> 
    <p>  
      <%= link_to 'View Logs', time_logs_path %>        
    </p> 
    <p>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
    </p>
  <% else %>
    <h1 class="home__header">Clock In-Out Application  </h1>
    <p>
      <%= link_to('Login', new_user_session_path) %>  
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClockTrackerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_logs.html.erb
<table>
  <tr>
    <th>Date</th>
    <th>Week Day</th>
    <th>Purpose</th>
    <th>Time In</th>
    <th>Time Out</th>
  </tr>
  <tr>
    <td><%= time_log.time_in.strftime("%m/%d/%Y") %></td>
    <td><%= humanize_week_day(time_log.week_day) %></td>
    <td><%= humanize_purpose(time_log.purpose) %></td>
    <td><%= time_log.time_in.strftime("%I:%M%p") %></td>
    <td><%= time_log.time_out.strftime("%I:%M%p") if time_log.time_out.present?  %></td>
    <td><%= link_to "View Log", time_log_path(time_log.id) %></td>
  </tr>
</table>

app/views/time_logs/edit.html.erb
<%= simple_form_for @time_log do |f| %>
  <%= f.input :time_out %>
  <%= f.button :submit %>
<% end %>

app/views/time_logs/index.html.erb
<div>
  <h1>Most Recent Logs</h1>
  <%= link_to 'New Clock In', new_time_log_path %>
  <% @current_week_logs.map do |log| %> 
    <%= render partial: "shared/logs", locals: { time_log: log } %>
  <% end %> 
</div>

app/views/time_logs/new.html.erb
<%= simple_form_for @time_log do |f| %>
  <%= f.input :comments %>
  <%= f.input :week_day, collection:  TimeLog.week_days, default: 1 %>
  <%= f.input :purpose, collection: TimeLog.meal_times, default: 1 %>
  <%= f.input :time_in %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%=  f.hidden_field :organization_id, value: Organization.first.id %>
  <%= f.button :submit %>
<% end %>

app/views/time_logs/show.html.erb
<div>
  <%= link_to 'Back', :back %>
  <% if @time_log.time_out.nil? %>
    <%= link_to 'Clock Out', edit_time_log_path(@time_log.id) %>
  <% end %>

  <p><%= humanize_week_day(@time_log.week_day) %></p>
  <p><%= humanize_purpose(@time_log.purpose) %></p>
  <p><%= @time_log.time_in %></p>
  <p><%= @time_log.time_out %></p>
  <p><%= @time_log.comments %></p>
</div>